google/vector_math.dart

lib/src/vector_math/matrix4.dart
lib/src/vector_math_64/matrix4.dart

Rotation matrices around Y-axis rotate clockwise even though matrices around X or Z axis do counterclockwise.

Fix clockwise rotations in rotateY() and setRotationY().

---

lib/src/vector_math/vector2.dart
lib/src/vector_math/vector3.dart
lib/src/vector_math/vector4.dart
lib/src/vector_math_64/vector2.dart
lib/src/vector_math_64/vector3.dart
lib/src/vector_math_64/vector4.dart
test/vector_test.dart

#88 Fix VectorX.normalizeLength

---

lib/src/vector_math/vector.dart
lib/src/vector_math/vector3.dart
lib/src/vector_math_64/vector.dart
lib/src/vector_math_64/vector3.dart
test/vector_test.dart

Add methods to calculate the unsigned and signed angle between two vectors

Add methods to calculate the unsigned and signed angle between two vectors

---

lib/src/vector_math/sphere.dart
lib/src/vector_math_64/sphere.dart

Add documentation
Fix a bug in copyFrom (was not copying the radius)

Cleanup sphere class

---

lib/src/vector_math/quad.dart
lib/src/vector_math/triangle.dart
lib/src/vector_math_64/quad.dart
lib/src/vector_math_64/triangle.dart
lib/vector_math.dart
lib/vector_math_64.dart
test/quad_test.dart
test/triangle_test.dart

* Cleanup triangle class and add some tests
* Add quad class with tests
Missing license headers for quad.dart, triangle_test.dart and quad_test.dart, I will add them as soon as the open PR is merged.

Add quad class and cleanup triangle

---

lib/src/vector_math/matrix2.dart
lib/src/vector_math/matrix3.dart
lib/src/vector_math/matrix4.dart
lib/src/vector_math_64/matrix2.dart
lib/src/vector_math_64/matrix3.dart
lib/src/vector_math_64/matrix4.dart
test/matrix_test.dart

Add asserts to entry and setEntry as a out of bound without an exception would be possible.
Ironically there is a test that is going out of bounds but didn't failed previously and still works fine after fixing the bounds...

Add asserts to entry and setEntry as a out of bound without an exception would be possible.

---

lib/src/vector_math/vector2.dart
lib/src/vector_math/vector3.dart
lib/src/vector_math/vector4.dart
lib/src/vector_math_64/vector2.dart
lib/src/vector_math_64/vector3.dart
lib/src/vector_math_64/vector4.dart
test/vector2_test.dart
test/vector3_test.dart
test/vector4_test.dart

Added some methods from three.js

Vector methods

---

lib/src/vector_math/matrix2.dart
lib/src/vector_math_64/matrix2.dart
test/matrix2_test.dart

- Same procedure as for the vectors
- Add Matrix2.scaled() and scale() with tests

Cleanup matrix2

---

lib/src/vector_math/matrix3.dart
lib/src/vector_math_64/matrix3.dart
test/matrix3_test.dart

Cleanup matrix3

---

lib/src/vector_math/vector2.dart
lib/src/vector_math/vector3.dart
lib/src/vector_math/vector4.dart
lib/src/vector_math_64/vector2.dart
lib/src/vector_math_64/vector3.dart
lib/src/vector_math_64/vector4.dart
test/vector2_test.dart
test/vector3_test.dart
test/vector4_test.dart

A simple change that adds an == operator to the vector classes. Useful some times for comparisons.

Added an equals operator for the vector classes.

---

lib/src/vector_math/opengl.dart
lib/src/vector_math_64/opengl.dart

* Use triple slash doc comments (///) like we do everywhere else
* Replace makePerspectiveMatrix implementation with a call to setPerspectiveMatrix (no need to maintain that implementation twice)
* Replace num with double where appropriate
* Format using dart format

Cleanup opengl

---

lib/src/vector_math/matrix4.dart
lib/src/vector_math_64/matrix4.dart

Cleanup matrix4

---

lib/src/vector_math/aabb3.dart
lib/src/vector_math/obb3.dart
lib/src/vector_math_64/aabb3.dart
lib/src/vector_math_64/obb3.dart
lib/vector_math.dart
lib/vector_math_64.dart
test/obb3_test.dart
test/test_all.dart

Basic obb3 class with some common methods and intersection tests.

Add obb3 class

---

lib/src/vector_math/vector2.dart
lib/src/vector_math/vector3.dart
lib/src/vector_math/vector4.dart
lib/src/vector_math_64/vector2.dart
lib/src/vector_math_64/vector3.dart
lib/src/vector_math_64/vector4.dart
test/vector2_test.dart
test/vector3_test.dart
test/vector4_test.dart

This PR replaces #66 but is implemented as setters instead of a setLength method.

Implement a length setter in vector2, vector3 and vector4

---

lib/src/vector_math_lists/vector2_list.dart
lib/src/vector_math_lists/vector3_list.dart
lib/src/vector_math_lists/vector4_list.dart
lib/src/vector_math_lists/vector_list.dart

VectorList store and load is currently implemented in the base class using a loop in a generic way. This PR moves the implementation into the derived classes. Tests with benchmarks of my application showed a big speedup.

VectorList store and load performance

---

pubspec.yaml
test/aabb2_test.dart
test/aabb3_test.dart
test/colors_test.dart
test/frustum_test.dart
test/geometry_test.dart
test/matrix2_test.dart
test/matrix3_test.dart
test/matrix4_test.dart
test/noise_test.dart
test/obb3_test.dart
test/opengl_matrix_test.dart
test/plane_test.dart
test/quad_test.dart
test/quaternion_test.dart
test/ray_test.dart
test/sphere_test.dart
test/test_utils.dart
test/triangle_test.dart
test/utilities_test.dart
test/vector2_list_test.dart
test/vector2_test.dart
test/vector3_list_test.dart
test/vector3_test.dart
test/vector4_list_test.dart
test/vector4_test.dart

Eliminates a deprecation warning

use test package directly

---

lib/src/vector_math_lists/scalar_list_view.dart
lib/vector_math_lists.dart
test/scalar_list_view_test.dart
test/test_all.dart

#81 Implement a view for Float32List that allows to specify a stride and an offset.
I'm open for a better name than Float32ListView, however Vector1List might implie that it implements VectorList which it doesn't do (as it is not possible).

Float32ListView

---

test/aabb2_test.dart

There were some minor typos and also the `testAabb2SetCenterAndHalfExtents` test was not actually testing the `setCenterAndHalfExtents` method at all.

Small fixes in the Aabb2 tests.

---

changelog.md

I think many people will use IntelliJ IDEA in the future, so add that folder to ingore list.
Fix a minor type in changelog.md

Update gitignore for Intellij

---

lib/src/vector_math/colors.dart
lib/src/vector_math_64/colors.dart
lib/src/vector_math_64/matrix3.dart
lib/src/vector_math_64/matrix4.dart
test/colors_test.dart

Colors.toHexString()

---

lib/src/vector_math/vector2.dart
lib/src/vector_math/vector3.dart
lib/src/vector_math/vector4.dart
lib/src/vector_math_64/vector2.dart
lib/src/vector_math_64/vector3.dart
lib/src/vector_math_64/vector4.dart
test/vector2_test.dart
test/vector3_test.dart
test/vector4_test.dart

See #170 
The code generation tool has added some code to the 64bit float library that did not exists before (someone forgot to run it?). The formatting of some parts is also altered since I ran `dartfmt`.

Vector*.random constuctor

---

README.md
lib/src/vector_math/matrix4.dart
lib/src/vector_math/vector2.dart
lib/src/vector_math/vector3.dart
lib/src/vector_math/vector4.dart
lib/src/vector_math_64/matrix4.dart
lib/src/vector_math_64/vector2.dart
lib/src/vector_math_64/vector3.dart
lib/src/vector_math_64/vector4.dart
lib/src/vector_math_geometry/generators/circle_generator.dart
lib/src/vector_math_geometry/generators/cube_generator.dart
lib/src/vector_math_geometry/generators/cylinder_generator.dart
lib/src/vector_math_geometry/generators/geometry_generator.dart
lib/src/vector_math_geometry/generators/ring_generator.dart
lib/src/vector_math_geometry/generators/sphere_generator.dart
lib/src/vector_math_geometry/mesh_geometry.dart

This PR:
- makes some expressions use null-aware syntax for better readability;
- fixes a bug in `MeshGeometry.copy` constructor.

Style tweaks and bugfix

---

changelog.md
lib/src/vector_math/constants.dart
lib/src/vector_math/quaternion.dart
lib/src/vector_math/vector.dart
lib/src/vector_math_64/constants.dart
lib/src/vector_math_64/quaternion.dart
lib/src/vector_math_64/vector.dart
lib/src/vector_math_geometry/generators/circle_generator.dart
lib/src/vector_math_geometry/generators/cylinder_generator.dart
lib/src/vector_math_geometry/generators/ring_generator.dart
lib/src/vector_math_geometry/generators/sphere_generator.dart
pubspec.yaml
test/aabb2_test.dart
test/matrix2_test.dart
test/matrix3_test.dart
test/matrix4_test.dart
test/obb3_test.dart
test/opengl_matrix_test.dart
test/quaternion_test.dart
test/utilities_test.dart
test/vector2_test.dart
test/vector3_test.dart

I'm not sure how these got missed on the first go around, but here's the rest of them.
Thanks!

Fix more Dart 2 core library constant names.

---

README.md

Remove getting started and doc links – these are provided on the pub site

readme: Remove gratuitous title

---

benchmark/matrix4_tween_bench.dart
benchmark/matrix_bench.dart
bin/mesh_generator.dart
test/aabb2_test.dart
test/aabb3_test.dart
test/colors_test.dart
test/frustum_test.dart
test/geometry_test.dart
test/matrix2_test.dart
test/matrix3_test.dart
test/matrix4_test.dart
test/noise_test.dart
test/obb3_test.dart
test/opengl_matrix_test.dart
test/plane_test.dart
test/quad_test.dart
test/quaternion_test.dart
test/ray_test.dart
test/scalar_list_view_test.dart
test/sphere_test.dart
test/test_utils.dart
test/triangle_test.dart
test/utilities_test.dart
test/vector2_list_test.dart
test/vector2_test.dart
test/vector3_list_test.dart
test/vector3_test.dart
test/vector4_list_test.dart
test/vector4_test.dart

No longer needed. Adds no benefit.

Remove gratuitous library declarations

---

.travis.yml
changelog.md
lib/src/vector_math_geometry/filters/barycentric_filter.dart
lib/src/vector_math_geometry/filters/flat_shade_filter.dart
pubspec.yaml
tool/travis.sh

- Update version
- Update sdk constraints
- Update travis config

prep for merge into master

---

lib/src/vector_math/aabb2.dart
lib/src/vector_math/aabb3.dart
lib/src/vector_math_64/aabb2.dart
lib/src/vector_math_64/aabb3.dart
lib/src/vector_math_geometry/generators/circle_generator.dart
lib/src/vector_math_geometry/generators/cube_generator.dart
lib/src/vector_math_geometry/generators/ring_generator.dart

I did a review of the changes and found some more oddities and errors similar to the one in https://github.com/google/vector_math.dart/pull/226.

additional nnbd fixes

---

CHANGELOG.md
pubspec.yaml

This will be published and depended on by flutter in a cherry pick for the 2.9.x stable release.

allow the 2.9 stable sdk and bump version

---

CHANGELOG.md
analysis_options.yaml
pubspec.yaml

Since opted in, this experiment is redundant.
/cc @kevmoo @natebosch

remove redundant experiment

---

.travis.yml
CHANGELOG.md
analysis_options.yaml
pubspec.yaml

Cleanup changelog
Test on latest supported stable SDK

Support latest dependencies, cleanup analysis options

---

lib/src/vector_math/quad.dart
lib/src/vector_math_64/quad.dart
test/quad_test.dart

Fix Quad.copy constructor not copying point3 correctly

---

.github/dependabot.yaml
.github/workflows/ci.yml
README.md

- add our standard markdown badges
- update the github actions CI versions
- configure dependabot to automatically move the actions versions forward

add markdown badges; configure dependabot

---

lib/src/vector_math/vector2.dart
lib/src/vector_math_64/vector2.dart

https://github.com/google/vector_math.dart/pull/294#discussion_r1210672558

fix: Revert negation change for Vector2
