lib/src/vector_math/matrix4.dart, test/matrix_test.dart
There was already a getter available but it retured a new instance and doesn't allow to reuse a existing Matrix3.
Also added a test
=> Add a method for copying the rotation part of a Matrix4

lib/src/vector_math/matrix4.dart, lib/src/vector_math_64/matrix4.dart, test/matrix_test.dart
A perspective transform is quite a common operation, but at t´most of the time one needs a 3 dimensional vector. At the moment it is required to create a 4 dimensional one with w set to 1, to the transformation, divide by w, that create a 3 dimensional vector again. The new method does everything in one go.
=> Add perspective transform to Matrix4

lib/src/vector_math/quaternion.dart
* Make storage private.
* Replace most constructors by factory constructors that use the set* method with the same behavior. This allows users of the class to reuse existing instances.
* Inline storages of arguments passed into methods to allow more optimizations by dart2js.
=> Cleanup quaternion

lib/src/vector_math/constants.dart, lib/src/vector_math/utilities.dart, lib/src/vector_math_64/constants.dart, lib/src/vector_math_64/utilities.dart, lib/vector_math.dart, lib/vector_math_64.dart, lib/vector_math_geometry.dart, lib/vector_math_lists.dart, lib/vector_math_operations.dart
Rename constants back to lowerCase the style guide was changed, they were already lowerCase previously.
I also added top level documentation for the library files. The vector_math.dart file references some classes that aren't available yet, but will come it a PR that adds them soon.
=> Rename constants back to lowerCase

README.md, lib/src/vector_math/ray.dart, lib/src/vector_math_64/quad.dart, lib/src/vector_math_64/ray.dart, test/ray_test.dart
* Improve performance of intersection tests by avoiding allocations. This is archived by creating static variables that are reused on every execution.
* Remove unnecessary type annotations in ray_test
* Fix link in readme, was missing http://
=> Cleanup ray class

lib/src/vector_math/frustum.dart, lib/src/vector_math_64/frustum.dart, test/frustum_test.dart
Don't use a list of planes, put the planes directly into the class
Use factory constructors
=> Cleanup frustum

lib/src/vector_math/aabb2.dart, lib/src/vector_math/aabb3.dart, lib/src/vector_math/vector2.dart, lib/src/vector_math_64/aabb2.dart, lib/src/vector_math_64/aabb3.dart, lib/src/vector_math_64/vector2.dart, test/aabb2_test.dart, test/aabb3_test.dart
* Add more constructors / setters to create a Aabb from another volumes (e.g. spheres).
* Remove type annotations in aabb tests, they only make reading them hard
* Add the corresponding tests
The code already contains some future changes Vector2 as the PR depends on them. The next PR will take a focus on Vector2.
=> Cleanup aabb

lib/src/vector_math/vector2.dart, lib/src/vector_math_64/vector2.dart, test/vector2_test.dart
- Remove duplicate implementation of some operations: they now delegate calls to another other method (e.g. add operator vs add method or length and length2). Inlining should make the whole thing perform as it did before.
- When a Vector is a argument, only get its storage once.
- Always access the private storage variable, this is a preparation for a future change.
- Doc comments.
- Making the shuffle getters aliases help to reduce the lines of the file, but the impact for Vector2 is quite small compated to Vector4.
=> Cleanup Vector2

lib/src/vector_math/vector2.dart, lib/src/vector_math/vector3.dart, lib/src/vector_math_64/vector2.dart, lib/src/vector_math_64/vector3.dart, test/vector3_test.dart
* More or less the same changes as to Vector2
* Move the Vector2 storage getter to the private field ;-)
=> Cleanup Vector3

lib/src/vector_math/vector4.dart, lib/src/vector_math_64/vector4.dart, test/vector4_test.dart
- Add additional constructors and their tests
- Always access private storage variable, inlining, remove duplicated code (as for Vector2)
- Make the color and tex-coord shuffle getters (rggb, tsss) delegating to the xyz variants. This is not designed as a performance improvement but should only make the code better to read and makes the file some (thousand) lines shorter.
=> Cleanup vector4

lib/src/vector_math/aabb3.dart, lib/src/vector_math/intersection_result.dart, lib/src/vector_math_64/aabb3.dart, lib/src/vector_math_64/intersection_result.dart, lib/vector_math.dart, lib/vector_math_64.dart, test/aabb3_test.dart
This PR implements a Aabb3 vs Triangle intersection. The implementation is based on the book Real Time Collision Detection. The test also provides more information about the type of intersection (intersection axis and penetration depth) if a IntersectionResult instance is provided when calling it.
To avoid allocations some internal used instances are implemented as preivate static variables and reused between invocations.
This PR also contains the unit test for the new feature.
This is a preperation for introducing a OBB type in the next PR (https://github.com/Fox32/vector_math/tree/feature/add-obb)
=> Add Aabb3 - Triangle intersection test

lib/src/vector_math/matrix2.dart, lib/src/vector_math/matrix3.dart, lib/src/vector_math/matrix4.dart, lib/src/vector_math/quaternion.dart, lib/src/vector_math/vector2.dart, lib/src/vector_math/vector3.dart, lib/src/vector_math/vector4.dart, lib/src/vector_math_64/matrix2.dart, lib/src/vector_math_64/matrix3.dart, lib/src/vector_math_64/matrix4.dart, lib/src/vector_math_64/quaternion.dart, lib/src/vector_math_64/vector2.dart, lib/src/vector_math_64/vector3.dart, lib/src/vector_math_64/vector4.dart
=> Use unique names for private storage fields in Vector(2,3,4), Matrix(2,3,4)

lib/src/vector_math/matrix2.dart, lib/src/vector_math/matrix3.dart, lib/src/vector_math/matrix4.dart, lib/src/vector_math/vector2.dart, lib/src/vector_math/vector3.dart, lib/src/vector_math/vector4.dart, lib/src/vector_math_64/matrix2.dart, lib/src/vector_math_64/matrix3.dart, lib/src/vector_math_64/matrix4.dart, lib/src/vector_math_64/vector2.dart, lib/src/vector_math_64/vector3.dart, lib/src/vector_math_64/vector4.dart, lib/vector_math.dart, lib/vector_math_64.dart, pubspec.yaml, test/matrix2_test.dart, test/matrix3_test.dart, test/matrix4_test.dart, test/vector2_test.dart, test/vector3_test.dart, test/vector4_test.dart
As requested in #147
First I fixed the equals operator implementation of the `VectorN` classes. When comparing with instances from other types they would crash instead of returning false as expected. [From the Dart Object == operator doc: "Total: It must return a boolean for all arguments. It should never throw or return null."](https://api.dartlang.org/apidocs/channels/stable/dartdoc-viewer/dart:core.Object#id_==)
Afterwards I implemented the equals operator for the `MatrixN` classes and the corresponding tests.
We should also implement `hashCode` to maintain consistency. We could use [quivers hash helpers](https://github.com/google/quiver-dart/blob/master/lib/src/core/hash.dart#L20) here, but that would add a new dependency. Should I also include this change in the PR?
=> Equals operator for matrixN classes

lib/src/vector_math/quaternion.dart, lib/src/vector_math_64/quaternion.dart, test/quaternion_test.dart
Two (small) changes in here:
- Bug fix in how axes are extracted from Quaternions. The denominator of the scaling factor should have a square root, otherwise it won't return the input axis for rotations != PI. I also changed it to check for a degenerate denominator (from a 0 rotation) to prevent blow-up.
- New factory to construct a Quat from two vectors. Pretty common operation. Also checks for the edge cases (0 rotation and PI rotation).
I also added tests for both.
=> Quaternion bug fix + construction from two vectors

changelog.md, lib/src/vector_math/vector2.dart, lib/src/vector_math_64/vector2.dart, test/vector2_test.dart
This methods were already available on Vector3, but I'm missing them on Vector2.
=> Vector.angleTo and angleToSigned

lib/src/vector_math/opengl.dart, lib/src/vector_math_64/opengl.dart, test/opengl_matrix_test.dart
This PR:
1. Speeds up `setPerspectiveMatrix` by inlining simplified version of `setFrustumMatrix` (less operations, less function calls). It gives ~11% speed boost in dart2js compiled version.
2. Adds support for infinite projection matrices.
> Tightening the Precision of Perspective Rendering
> Paul Upchurch, Mathieu Desbrun
> Journal of Graphics Tools, Volume 16, Issue 1, 2012
=> Speedup perspective matrix, add infinite projection

lib/src/vector_math/matrix4.dart, test/matrix4_test.dart
I'm open to alternate method names and to making this an instance method instead of a static method.
I've made this a static method as that appears more consistent with the existing API where instance methods modify the matrix instead of returning a new matrix.
Having this method will be nice for flutter as there are cases hit testing where it is fine for a matrix to be non-invertible. Throwing an exception means running a flutter app with a transform matrix like `scale(0.0) ` with "pause on caught exceptions" will pause frequently.
=> Add Matrix4.tryToInvert static method to support trying to invert a matrix without throwing an exception.

lib/src/vector_math_geometry/mesh_geometry.dart, test/geometry_test.dart
Bug fix in MeshGeometry.combine that corrects indexing (previous was incrementing index offset by the size of the vertex buffer, new increments by number of vertices).
=> Fixed indexing bug in MeshGeometry.combine

changelog.md, lib/src/vector_math/matrix4.dart, lib/src/vector_math_64/matrix4.dart
The reduction in allocations improves the performance of the Matrix4Tween benchmarks by roughly 20%
JIT VM
Matrix4TweenBenchmark1(RunTime): 6488.954692556635 us.
Matrix4TweenBenchmark2(RunTime): 4512.9009009009005 us.
Matrix4TweenBenchmark3(RunTime): 4744.867298578199 us.
--->
Matrix4TweenBenchmark1(RunTime): 5072.906329113924 us.
Matrix4TweenBenchmark2(RunTime): 3204.7952 us.
Matrix4TweenBenchmark3(RunTime): 3394.628813559322 us.
JSC:
Matrix4TweenBenchmark1(RunTime): 12300.613496932516 us.
Matrix4TweenBenchmark2(RunTime): 9578.947368421053 us.
Matrix4TweenBenchmark3(RunTime): 7347.985347985348 us.
--->
Matrix4TweenBenchmark1(RunTime): 10287.179487179486 us.
Matrix4TweenBenchmark2(RunTime): 7948.412698412699 us.
Matrix4TweenBenchmark3(RunTime): 5717.142857142857 us.
Chrome 74:
Chrome has …
=> Reuse Matrix3, Matrix4 and Vector3 in decompose

.gitignore, benchmark/matrix_bench.dart, lib/src/vector_math/aabb2.dart, lib/src/vector_math/aabb3.dart, lib/src/vector_math/matrix3.dart, lib/src/vector_math_64/aabb2.dart, lib/src/vector_math_64/aabb3.dart, lib/src/vector_math_64/matrix3.dart
Improve consistency in avoiding public getters in a number of methods.
Add benchmarks for affected code to ensure positive performance impact.
Aabb2.transform is about 11% faster with these changes.
Aabb2.rotate is about 17% faster with these changes.
The rest of the changes had no measurable benchmark impact, but improve
consistency in the source base.
(Added .idea directory from IntelliJ/Android Studio to .gitignore)
=> Reuse temp variables in Aabb2.transform methods.

LICENSE
The license from `lib/src/vector_math/noise.dart` needs to be copied into the top level license before this can be rolled internally.
=> append additional license

lib/src/vector_math_geometry/generators/cylinder_generator.dart
This caused issues on the internal roll, the fields were moved to be final as a part of the NNBD migration but can be set multiple times.
=> remove final declaration for non-final fields

.github/workflows/ci.yml, CHANGELOG.md, lib/hash.dart, lib/src/vector_math/matrix2.dart, lib/src/vector_math/matrix3.dart, lib/src/vector_math/matrix4.dart, lib/src/vector_math/vector2.dart, lib/src/vector_math/vector3.dart, lib/src/vector_math/vector4.dart, lib/src/vector_math_64/matrix2.dart, lib/src/vector_math_64/matrix3.dart, lib/src/vector_math_64/matrix4.dart, lib/src/vector_math_64/vector2.dart, lib/src/vector_math_64/vector3.dart, lib/src/vector_math_64/vector4.dart, lib/vector_math.dart, lib/vector_math_64.dart, pubspec.yaml
- Collapse pre-release versions in changelog
- Deprecate hash.dart library, prepare to release v2.1.1
=> use object hash

.github/workflows/ci.yml
=> CI: Remove explicit --packages arg to coverage

CHANGELOG.md, lib/src/vector_math/matrix2.dart, lib/src/vector_math/matrix3.dart, lib/src/vector_math/matrix4.dart, lib/src/vector_math/vector2.dart, lib/src/vector_math/vector3.dart, lib/src/vector_math/vector4.dart, lib/src/vector_math_64/matrix2.dart, lib/src/vector_math_64/matrix3.dart, lib/src/vector_math_64/matrix4.dart, lib/src/vector_math_64/vector2.dart, lib/src/vector_math_64/vector3.dart, lib/src/vector_math_64/vector4.dart, pubspec.yaml
The null value will never be passed to the equals operator
implementation. Widening the type causes any other class which
implements this interface to also widen the type.
=> Use non-nullable parameters for operator ==

CHANGELOG.md, README.md, lib/src/vector_math/third_party/noise.dart, lib/src/vector_math_64/third_party/noise.dart, lib/vector_math.dart, lib/vector_math_64.dart, test/noise_test.dart
- deprecate the two SimplexNoise classes
- update the changelog entry for `2.1.3` (which has not yet been published)
This is work towards https://github.com/google/vector_math.dart/issues/270; deprecating and eventually removing the SimplexNoise classes.
=> deprecate the SimplexNoise classes

lib/src/vector_math/quaternion.dart, lib/src/vector_math_64/quaternion.dart
Adds an operator== to Quaternion so that two instances of quaternions can be evaluated for equality.
I didn't see a unit test for this comparable functionality in Vector3, so assumed it's trivial enough, but can add one if desired.
=> Add operator== to Quaternion

benchmark/vector2_bench.dart
> I worry that these changes may confuse the (somewhat brittle) analysis that allow the length of _v3storage to sometimes become known in the optimizer.
Due to this comment https://github.com/google/vector_math.dart/pull/294#issuecomment-1568937625 I wanted to make sure that it wasn't slower to create `Vector2` objects with named constructors than with "redirecting" factory constructors. The benchmark shows no sign of it being slower than before.
@rakudrama is there anything I should change, or add, in the benchmark?
=> `Vector2` constructor benchmark

lib/src/vector_math/matrix3.dart, lib/src/vector_math_64/matrix3.dart, test/matrix3_test.dart
Current implementation rotates clockwise which is not the norm and not consistent to the implemented X and Y rotation matrices.
This PR fixes issue #261 .
=> Fix rotation around Y axis

lib/src/vector_math/matrix3.dart, lib/src/vector_math_64/matrix3.dart, test/matrix3_test.dart
Reverts google/vector_math.dart#262
- Broke some tests
- Made the method inconsistent with the Matrix4 code.
=> Revert "Fix rotation around Y axis"

lib/src/vector_math/vector2.dart, lib/src/vector_math_64/vector2.dart
This reverts back the named constructors of Vector2 to factory constructors so that we can continue with the the Vector3 and Vector4 changes in #294 and #295.
Ping @rakudrama and @johnmccutchan, the other PRs are also updated to remove the named constructors.
=> fix: Revert Vector2 constructor changes

lib/src/vector_math/vector3.dart, lib/src/vector_math_64/vector3.dart
Since the `Vector3.zero` constructor was already a normal named constructor it was already possible to extend the class.
- ~~Converts all factory constructors (except `Vector3.random`) to named constructors that directly sets the storage instead of calling intermediary methods to do it.~~
- Simplifies `length2`, `dot`, `isInfinite` and `isNaN`.
- Optimizes `reflect`, `relativeError` and `absoluteError` so that they don't create extra `Vector3` objects.
- Orders all operations made on `_v3storage` from 1 to 0 so that it is consistent across the class and guarantees that bounds checking is only done once.
=> Some general Vector3 optimizations

lib/src/vector_math/vector4.dart, lib/src/vector_math_64/vector4.dart
Since the `Vector4.zero` constructor was already a normal named constructor it was already possible to extend the class.
- ~~Converts all factory constructors (except `Vector4.random`) to named constructors that directly sets the storage instead of calling intermediary methods to do it.~~
- Simplifies `length2`, `dot`, `isInfinite` and `isNaN`.
- Optimizes `reflect`, `relativeError` and `absoluteError` so that they don't create extra `Vector4` objects.
- Orders all operations made on `_v4storage` from 1 to 0 so that it is consistent across the class and guarantees that bounds checking is only done once.
=> Some general Vector4 optimizations

lib/src/vector_math/quad.dart, lib/src/vector_math/vector4.dart, lib/src/vector_math_64/quad.dart, lib/src/vector_math_64/vector4.dart, test/quad_test.dart
and minor fix to the vector4 toString
=> Added a toString, operator == and hashCode to the Quad class.

README.md
I was originally confused which to import, 'package:vector_math/vector_math.dart' or 'package:vector_math/vector_math_64.dart'. After reading the code, I figured a minor update to the readme might be helpful.
If there was somewhere more appropriate, or a better way to express this I'm happy to make changes.
=> Update README.md to show how to use vector_math_64.

CHANGELOG.md, lib/src/vector_math/matrix3.dart, lib/src/vector_math_64/matrix3.dart, test/matrix3_test.dart, test/obb3_test.dart
This PR addresses the issues highlighted in #261 and is related to the discussions in #262 and #300, as well as the historical context provided by #69.
In reference to the conversation in [#262](https://github.com/google/vector_math.dart/pull/262#issuecomment-1651969704), two primary concerns were identified:
1. The change introduced test failures.
2. There was an inconsistency between the `rotateY` methods in the `Matrix3` and `Matrix4` classes.
Here's a summary of the remedial actions taken in this PR:
This PR is similar to #262. The only difference is that this PR also includes a negated rotation angle in the `obb3` test.
For issue (1), the test expectations have been updated to reflect the correct signs, ensuring that all tests now pass.
Regarding issue (2), upon further …
=> Resolve Inconsistency in Matrix3 and Matrix4 `rotateY` Implementations

CHANGELOG.md, lib/src/vector_math/quaternion.dart, lib/src/vector_math_64/quaternion.dart, test/quaternion_test.dart
=> Fix quaternion negate

.github/dependabot.yaml, .github/workflows/ci.yml, .github/workflows/no-response.yml, .github/workflows/publish.yaml
This PR contains changes created by the blast repo tool.
- `auto-publish`
- `dependabot`
- `github-actions`
- `no-response`
=> blast repo changes: auto-publish, dependabot, github-actions, no-response

benchmark/vector2_bench.dart
Partial fix for benchmarks.
The thing is that in some microbenchmarks the calculation result is not used in any way, because of this the compiler simply "optimizes the benchmark" by throwing away the payload.
Most of the current benchmark implementations literally measure the air in an empty room.
I can only partially fix them, I think for further fixes you should ask Vyacheslav Egorov for advice.
https://mrale.ph/blog/2021/01/21/microbenchmarking-dart-part-1.html
https://mrale.ph/blog/2024/11/27/microbenchmarks-are-experiments.html
```bash
$ dart run benchmark/vector2_bench.dart
```
|                           | Before                 | After                  |
| ------------------------- | ---------------------- | ---------------------- |
| Vector2()                 | 202.8197194309024 …
=> Partial fix for benchmarks.

CHANGELOG.md, benchmark/matrix_bench.dart, lib/src/vector_math/matrix2.dart, lib/src/vector_math/matrix3.dart, lib/src/vector_math/matrix4.dart, lib/src/vector_math/opengl.dart, lib/src/vector_math_64/matrix2.dart, lib/src/vector_math_64/matrix3.dart, lib/src/vector_math_64/matrix4.dart, lib/src/vector_math_64/opengl.dart, pubspec.yaml, test/geometry_test.dart, test/matrix4_test.dart
`Matrix4.translate` is used by Flutter and it often appears as an overhead when
profiling Flutter apps compiled to Wasm.
The function currently takes a `dynamic` argument and takes different code
paths based on the type.
This is inefficient when the call site already knows the argument's type.
In general, when we have a performance-critical generic function that checks
types of the arguments, it makes sense to introduce specialized versions of the
function based on precise argument types that it handles, so that callers can
call the more efficient specialized versions and avoid the type test overheads.
For each function with `dynamic` argument, this PR introduces specialized
functions based on precise argument types that the functions handle, call those
specialized functions from the …
=> Improve performance of functions with dynamic arguments
